on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag (X.Y.Z) to release from"
        required: true
      commit_message:
        description: "Additional commit message for the release commit (optional)"
        required: false

env:
  OriginalRepo: ETLCPP/etl.git
  ReleaseBranch: release

  SrcCodeDir: original
  ReleaseDir: release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify the tag
        run: |
          if [[ ! ${{ github.event.inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: It must be a tag in the format X.Y.Z"
            exit 1
          fi

      - name: Checkout the original repo
        uses: actions/checkout@v6
        with:
          path: ${{ env.SrcCodeDir }}
          repository: ${{ env.OriginalRepo }}
          ref: ${{ github.event.inputs.tag }}
          sparse-checkout: |
            include/etl/
            LICENSE
            README.md
            version.txt
          sparse-checkout-cone-mode: false  # Disable cone mode to allow for checking out single files

      - name: Checkout the release repo
        uses: actions/checkout@v6
        with:
          path: ${{ env.ReleaseDir }}
          ref: ${{ env.ReleaseBranch }}

      - name: Clean the release repo
        run: |
          mv ${{ env.ReleaseDir }}/.git ./ReleaseGitBackup
          rm -rf ${{ env.ReleaseDir }}/*
          mv ./ReleaseGitBackup ${{ env.ReleaseDir }}/.git

          echo "Cleaned the release directory. The release directory now contains:"
          ls -A ${{ env.ReleaseDir }}

      - name: Construct the release
        run: |
          #  (+) 此处使用 `*`，将不会匹配 `.` 开头的隐藏文件和目录
          #      目前（20.47.1）有且只有 `./include/etl/.vscode` 目录，被排除符合预期。
          mv ${{ env.SrcCodeDir }}/include/etl/* ${{ env.ReleaseDir }}/
          mv ${{ env.SrcCodeDir }}/LICENSE ${{ env.ReleaseDir }}/
          mv ${{ env.SrcCodeDir }}/README.md ${{ env.ReleaseDir }}/
          mv ${{ env.SrcCodeDir }}/version.txt ${{ env.ReleaseDir }}/

          echo "Finished constructing the release. The release directory now contains:"
          ls -A ${{ env.ReleaseDir }}

      - name: Release
        working-directory: ${{ env.ReleaseDir }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Release ${{ github.event.inputs.tag }}${{ github.event.inputs.commit_message && format(' ({0})', github.event.inputs.commit_message) }}"
          git push origin ${{ env.ReleaseBranch }}
